add TestSortMap
iotexproject/iotex-core pull request #2597
Opened 2021-04-06 03:24 UTC by millken

2021-04-09 02:10 UTC, dustinxie commented
the fix in https://github.com/iotexproject/iotex-core/commit/495fc835841921d76aa3ecfb294c86e4e8c81905 took effect in Snapshot() and RevertToSnapshot()
so we'll need a test to trigger code in these 2 funcs, before the fix, the trie root hash will change in you run the test multiple (like 20) times. after the fix, the root hash keep fixed

2021-04-09 02:15 UTC, dustinxie commented
the fix in https://github.com/iotexproject/iotex-core/commit/495fc835841921d76aa3ecfb294c86e4e8c81905 took effect in Snapshot() and RevertToSnapshot()

so we need a piece of code that can trigger these 2 funcs to make multiple entries in the map, then run the code multiple (like 20) times. before the fix, the trie root hash will change. after the fix, the trie root hash will keep fixed

2021-04-26 21:33 UTC, CoderZhi requested changes
This unit test should be against StateDBAdapter.Snapshot() and RevertToSnapshot() with sortCachedContracts as true or false. When it is set to true, the behavior is constant, if false, the behavior may be inconstant (you can run it for several times, and asset that is some inconsistency).

2021-04-26 21:33 UTC, CoderZhi commented on action/protocol/execution/evm/evmstatedbadapter_test.go
> +			require.NotEqual(t1, testHash1(cMap))
this is not always true

2021-08-20 05:10 UTC, dustinxie commented on action/protocol/execution/evm/evmstatedbadapter_test.go
> +				c := stateDB.cachedContract[addr]
why we calculate each contract's root? is there an entire root to check?

from your test result, it seems correct to do this. maybe confirm with Zhi as well

2021-08-21 03:41 UTC, CoderZhi approved these changes

2021-08-24 01:45 UTC, dustinxie approved these changes

2021-08-24 01:52 UTC, merged