add acount delete test
iotexproject/iotex-core pull request #2686
Opened 2021-05-27 11:36 UTC by leyafo

2021-05-27 11:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iotexproject/iotex-core?pullRequest=2686) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iotexproject/iotex-core?pullRequest=2686) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iotexproject/iotex-core?pullRequest=2686) it.</sub>

2021-05-27 15:56 UTC, CoderZhi approved these changes

2021-05-27 15:56 UTC, CoderZhi commented on ioctl/cmd/account/account_test.go
> -
revert

2021-05-27 16:01 UTC, CoderZhi requested changes
=== RUN   TestAccountDelete
    TestAccountDelete: account_test.go:125: 
        	Error Trace:	account_test.go:125
        	Error:      	Should be true
        	Test:       	TestAccountDelete
--- FAIL: TestAccountDelete (1.81s)

2021-06-25 00:56 UTC, dustinxie commented
closed due to inactivity

2021-06-25 00:56 UTC, closed without merging