[api] add tracing events for slow api
iotexproject/iotex-core pull request #3057
Opened 2022-02-07 10:33 UTC by millken

2022-02-07 17:56 UTC, Liuhaai commented on actpool/actpool.go
>  		ap.updateAccount(sender)
Could you add one more trace here?

2022-02-07 17:56 UTC, Liuhaai approved these changes

2022-02-07 20:41 UTC, CoderZhi requested changes

2022-02-07 20:41 UTC, CoderZhi commented on api/coreservice.go
> +func (core *coreService) Account(ctx context.Context, addr address.Address) (*iotextypes.AccountMeta, *iotextypes.BlockIdentifier, error) {
revert

2022-02-07 20:41 UTC, CoderZhi commented on api/web3server_utils.go
> +	accountMeta, _, err := svr.coreService.Account(context.Background(), ioAddr)
revert

2022-02-07 20:41 UTC, CoderZhi commented on api/web3server.go
> +	accountMeta, _, err := svr.coreService.Account(context.Background(), ioAddr)
revert

2022-02-07 20:41 UTC, CoderZhi commented on api/grpcserver.go
> +	accountMeta, blockIdentifier, err := svr.coreService.Account(ctx, addr)
revert

2022-02-08 04:42 UTC, millken commented on api/coreservice.go
> +	ctx, span := tracer.NewSpan(ctx, "coreService.Account")
If so, will not know who called it

2022-02-09 00:15 UTC, CoderZhi approved these changes

2022-02-09 01:56 UTC, merged

2022-02-20 17:48 UTC, Scheusal13 reviewed
io168vpa7fn9xk3jerkjf4mjgdmcrg3hv8af9qncm