Dev prefix unexported globals with   by ioctl pkg
iotexproject/iotex-core pull request #3241
Opened 2022-03-28 19:10 UTC by LuckyPigeon

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-28 21:35 UTC, Liuhaai approved these changes

2022-03-31 19:13 UTC, CoderZhi requested changes

2022-04-01 02:29 UTC, CoderZhi approved these changes

2022-04-01 02:29 UTC, CoderZhi commented on ioctl/newcmd/alias/aliasimport.go
>  		"format=", "f", "json", flagImportFormatUsage)
@huof6829 `"format="` should be `"format"`?

2022-04-01 02:30 UTC, merged