[api] Remove ReceiptByAction() in coreservice.go
iotexproject/iotex-core pull request #3347
Opened 2022-04-19 03:50 UTC by LuckyPigeon

# Description

`ReceiptByAction()` is only used in `GetReceiptByAction()` in `grpcserver.go`

Fixes #3208 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] TestGrpcServer_GetReceiptByActionIntegrity

**Test Configuration**:

- Firmware version: Ubuntu 21.04
- Hardware:
- Toolchain:
- SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-19 06:14 UTC, Liuhaai commented on api/coreservice.go
> +	return core.getBlockHashByActionHash(h)
No need creates a new func. L989 can be converted into public func

2022-04-19 06:14 UTC, Liuhaai commented on api/grpcserver.go
> +	// receipt, blkHash, err := svr.coreService.ReceiptByAction(actHash)
remove

2022-04-19 06:14 UTC, Liuhaai commented on api/coreservice.go
> +		// GetBlockHashByActionHash returns public method for getBlockHashByActionHash
use the comment on L988 here

2022-04-25 16:43 UTC, Liuhaai approved these changes

2022-04-26 22:27 UTC, CoderZhi requested changes

2022-04-26 22:27 UTC, CoderZhi commented on api/coreservice.go
> +		GetBlockHashByActionHash(h hash.Hash256) (hash.Hash256, error)
BlockHashByActionHash

2022-04-26 22:27 UTC, CoderZhi commented on api/coreservice.go
> +		GetBlockHashByActionHash(h hash.Hash256) (hash.Hash256, error)
BlockHashByActionHash

2022-04-26 22:27 UTC, CoderZhi commented on api/grpcserver.go
> +	blkHash, err := svr.coreService.GetBlockHashByActionHash(actHash)
this is not efficient. you may consider to use `receipt.BlockHeight` and fetch the block hash by block height.

2022-05-25 18:10 UTC, CoderZhi approved these changes

2022-05-26 04:15 UTC, Liuhaai commented
@LuckyPigeon could you resolve the conflict?

2022-05-26 19:13 UTC, merged