add reward check in minicluster test
iotexproject/iotex-core pull request #3615
Opened 2022-08-29 06:40 UTC by huof6829

# Description

Fixes  https://github.com/iotexproject/iotex-core/issues/2901

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

2022-08-29 14:11 UTC, raullenchai approved these changes

2022-08-29 21:34 UTC, CoderZhi requested changes

2022-08-29 21:34 UTC, CoderZhi commented on tools/minicluster/minicluster.go
> +			registries[i] = svrs[i].ChainService(configs[i].Chain.ID).Registry()
will a local parameter sufficient?

2022-08-29 21:34 UTC, CoderZhi commented on tools/minicluster/minicluster.go
> +				log.S().Error("rolldpos is not registered.")
if `rp` is nil, how could line 415 works?

2022-08-30 16:36 UTC, CoderZhi commented on tools/minicluster/minicluster.go
> +				log.S().Error("Failed to get block reward.", zap.Error(err))
same problem here

2022-08-30 16:36 UTC, CoderZhi commented on tools/minicluster/minicluster.go
> +				log.S().Error("actual block reward is incorrect.")
and here

2022-08-30 16:36 UTC, CoderZhi commented on tools/minicluster/minicluster.go
> +				log.S().Error("Failed to get epoch reward.", zap.Error(err))
and here

2022-09-01 21:51 UTC, CoderZhi approved these changes

2022-09-02 10:10 UTC, merged