[api] forbid processing system action
iotexproject/iotex-core pull request #3867
Opened 2023-05-25 19:12 UTC by dustinxie

# Description
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-05-25 19:13 UTC, dustinxie commented on api/coreservice.go
> +	}
to prevent potential replay of grantreward

2023-05-25 23:58 UTC, Liuhaai approved these changes

2023-05-26 04:03 UTC, CoderZhi commented
https://github.com/iotexproject/iotex-core/blob/master/state/factory/workingset.go#L455

2023-05-26 04:16 UTC, envestcc approved these changes

2023-05-26 04:39 UTC, CoderZhi requested changes
It has been prevented in workingset

2023-05-26 05:41 UTC, dustinxie commented
> It has been prevented in workingset

yes, but that's after a block is proposed (and then found invalid), so a block is wasted. In other words, someone can potentially keep sending such a system action and prevent block being generated, like a DoS attack?

so it's worthwhile to early-detect this and throw it out of action pool?

2023-05-26 17:29 UTC, CoderZhi commented
> > It has been prevented in workingset
> 
> yes, but that's after a block is proposed (and then found invalid), so a block is wasted. In other words, someone can potentially keep sending such a system action and prevent block being generated, like a DoS attack?
> 
> so it's worthwhile to early-detect this and throw it out of action pool?

if so, we need to prevent adding it to actpool.

2023-05-30 01:44 UTC, dustinxie commented
> > > It has been prevented in workingset
> > 
> > 
> > yes, but that's after a block is proposed (and then found invalid), so a block is wasted. In other words, someone can potentially keep sending such a system action and prevent block being generated, like a DoS attack?
> > so it's worthwhile to early-detect this and throw it out of action pool?
> 
> if so, we need to prevent adding it to actpool.

yes, by early-exiting here, system action is neither added to local actpool (L436 below), nor being propagated to p2p network (L460 below)

2023-05-30 20:03 UTC, merged