[api] support "input" field in web3 request params
iotexproject/iotex-core pull request #3971
Opened 2023-11-16 08:47 UTC by envestcc

# Description

Fixes #3969

The following three web3 API support the latest Ethereum JSON-RPC specification, with parameters supporting `input` field:
- eth_call
- eth_estimateGas
- debug_traceCall

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

2023-11-16 16:37 UTC, Liuhaai approved these changes

2023-11-17 00:09 UTC, CoderZhi approved these changes

2023-11-18 00:30 UTC, CoderZhi requested changes
do we need hard fork?

2023-11-20 02:16 UTC, envestcc commented
> do we need hard fork?
confirmed that the three affected APIs are read-only, so a hard fork is not needed.

2023-11-20 03:18 UTC, CoderZhi approved these changes

2023-11-20 05:00 UTC, merged