[p2p] Reduce conns limit to 30-60
iotexproject/iotex-core pull request #4032
Opened 2023-12-22 03:13 UTC by envestcc

# Description

reduce p2p connections to reduce message traffic

## Type of change
Please delete options that are not relevant.
- [x] Code refactor or improvement

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

2023-12-22 05:04 UTC, CoderZhi approved these changes

2023-12-26 23:06 UTC, Liuhaai approved these changes

2023-12-26 23:07 UTC, Liuhaai commented on go.mod
> +replace github.com/iotexproject/go-p2p => github.com/iotexproject/go-p2p v0.3.6-0.20231222070751-203dad2e2816
unnecessary to update p2p package?

2024-01-16 12:47 UTC, CoderZhi requested changes
Don't merge before validating the change

2026-05-15 07:39 UTC, closed without merging