[blockindex] remove deprecated DeleteTipBlock
iotexproject/iotex-core pull request #4249
Opened 2024-04-23 01:03 UTC by envestcc

# Description

DeleteTipBlock has been deprecated, removing it from blockindexer

Fixes #(issue)

## Type of change
Please delete options that are not relevant.
- [x] Code refactor or improvement

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

2024-04-23 01:14 UTC, dustinxie commented
should have more places to remove this func, you can refer to earlier #3854

2024-04-23 16:49 UTC, Liuhaai requested changes

2024-04-23 16:49 UTC, Liuhaai commented on blockchain/blockdao/blockindexer.go
> -		DeleteTipBlock(context.Context, *block.Block) error
https://github.com/iotexproject/iotex-core/pull/2647

2024-04-23 16:50 UTC, Liuhaai commented on blockchain/blockdao/blockindexer.go
> -		DeleteTipBlock(context.Context, *block.Block) error
lmk if the early issue has been resolved

2024-04-23 17:17 UTC, dustinxie commented
we have 2 earlier PR (#2647 and #3854) trying to clean-up this.

IMO, `DeleteTipBlock` is a wrong method to start with, so it should be deleted. I propose let's use the earliest #2647 to finish this off. @Liuhaai  let us know

2024-05-07 02:28 UTC, envestcc commented
> we have 2 earlier PR (#2647 and #3854) trying to clean-up this.
> 
> IMO, `DeleteTipBlock` is a wrong method to start with, so it should be deleted. I propose let's use the earliest #2647 to finish this off. @Liuhaai let us know

Okay, use the previous and close this one

2024-05-07 02:28 UTC, closed without merging