[ioctl] fix -P flag ignoring password input
iotexproject/iotex-core pull request #4341
Opened 2024-07-22 22:23 UTC by dustinxie

# Description
as title

Fixes #4340 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

2024-07-23 15:00 UTC, envestcc approved these changes

2024-08-01 09:32 UTC, CoderZhi requested changes

2024-08-01 09:32 UTC, CoderZhi commented on ioctl/cmd/action/action.go
> +
move to `ioctl/cmd/account` to resolve cycle import issue

2024-08-07 01:05 UTC, CoderZhi approved these changes

2024-08-14 02:00 UTC, merged